import pandas as pd
import re


df = pd.read_csv(
    "data/raw_dataset.csv"
)


texts = []
labels = []


for row in df["essay"]:

    text = str(row)


    if "written by an actual student" in text:

        label = "student"

    elif "generated by a Large Language Model" in text:

        label = "llm"

    else:
        continue


    cleaned = re.sub(
        r"<.*?>",
        "",
        text
    )


    texts.append(cleaned)
    labels.append(label)



corpus = pd.DataFrame(
    {
        "text": texts,
        "label": labels
    }
)


corpus.to_csv(
    "data/processed_corpus.csv",
    index=False
)


print(
    corpus["label"].value_counts()
)